dependencies {
    compileOnly('com.github.GTNewHorizons:Navigator:1.1.8:dev') { transitive = false }
    compileOnly('info.journeymap:journeymap-api-forge:1.7.10-2.0.0')
    compileOnly('maven.modrinth:journeymap:5.2.20')
    compileOnly('curse.maven:xaeros-minimap-263420:5637000')
    compileOnly('curse.maven:xaeros-world-map-317780:5658209')
}
